version: 2.1
runners:
  slate:
    config-id: 3
jobs: 
  build:
    cwd: /catalyst
    steps:
        - echo "Initializing the deployment process..."
        - pwd
        - npm install zcatalyst-cli -s --force
        - echo "Installing the dependencies..."
        - npm install --force
        - echo "Building the app..."
        - npm run build
        - echo "Copying the build files to the deployment directory..."
        - mkdir -p /tmp/catalyst/.next && cp -r .next/* /tmp/catalyst/.next
        - cp app-config-prod.json /tmp/catalyst/app-config.json
        - cp catalyst.json /tmp/catalyst/catalyst.json
        - cd /tmp/catalyst
        - ls -latrh
        - catalyst deploy appsail

stages:
  - name: shareme
    jobs:
      - build