version: 2.1
runners:
  slate:
    config-id: 3
jobs: 
  build:
    cwd: /catalyst
    steps:
        - echo "Initializing the deployment process..."
        - pwd
stages:
  - name: build
    jobs:
      - build